version: '3.7'

services:

  php:
    build: './php/'
    container_name: laravel-php
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html

  pgsql:
    image: postgres:12.0-alpine
    container_name: laravel-pgsql
    working_dir: /data/pgsql
    volumes:
    - ./postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgdb
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend: